### PR TITLE
remove hardcoded path from require statement in KarmaEnvironment.coffee

### PR DESCRIPTION
**Pull request by tongfa**
I need this simple change in order to use karma-environments.  Other than this, it's working pretty good.  Running about 1600 unit tests through it in 12 environments.  It's just what I needed!

### CODE REVIEW

**Comment by Xiphe** [comment]
LGTM :beetle:

**Comment by Xiphe** [comment]
I'm having troubles releasing a new version since I have not touched this project in years

**Comment by Xiphe** [comment]
Wich version of node are you using this with?

**Comment by Xiphe** [comment]
I'll look into releasing a new version, and also updating dependencies later this day

**Comment by tongfa** [comment]
@Xiphe:

$ node --version
v6.10.1

thank you for merging!

Do you know Mark Gardener?  He used to work at the same company I work at.

**Comment by Xiphe** [comment]
released as `karma-environments@0.2.17`

No that name does not ring a bell, but im bad with names anyways 😕

**Comment by tongfa** [comment]
His name is in the readme for this project as a "shout out", is why I asked :-)

thanks again!

**Comment by Xiphe** [comment]
Ah, I see. No, we never spoke or met

**Comment by tongfa** [comment]
Wanted to let you know I was able to pull down the nodejs repo version of this package 0.2.19  and was able to successfully run it in our build environment, which is on linux.  For some odd reason, I had to manually add `coffee-script` to our package.json.  I didn't have to do this on my local environment.  Anyways, I am reporting success for:
Linux
MacOS
And also our tests are using mocha, and they work great.  ( I think the README only states Jasmine)
Our coverage tool Istanbul seems like it is susceptible to the same issue described in the README with karma-coverage, but that's OK.  Maybe we will fix it and provide another patch.

Thanks!

**Comment by Xiphe** [comment]
Sweet, thanks for the feedback!

**Pull request merged**
